// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaSD.DataAccess;

#nullable disable

namespace PruebaSD.DataAccess.EntityFrameworkDataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240903233331_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.7.24405.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PruebaSD.Entities.Entities.Usuario", b =>
                {
                    b.Property<decimal>("UsuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("usuID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("UsuID"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("UsuID");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuID = 1m,
                            Apellido = "Pérez",
                            Nombre = "Juan"
                        },
                        new
                        {
                            UsuID = 2m,
                            Apellido = "Gómez",
                            Nombre = "Ana"
                        },
                        new
                        {
                            UsuID = 3m,
                            Apellido = "Martínes",
                            Nombre = "Carlos"
                        },
                        new
                        {
                            UsuID = 4m,
                            Apellido = "Lopez",
                            Nombre = "María"
                        },
                        new
                        {
                            UsuID = 5m,
                            Apellido = "Marin",
                            Nombre = "Isabel"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
